const projects=[
 ['house','House','Personal website','Engineering, photography and the journal.',170,180],
 ['cleanr','Cleanr','AI / Email','An agent-assisted interface for managing IMAP inboxes.',690,110],
 ['spotapi','SpotAPI','Music / API','Listening history from Spotify, exposed through an API.',690,290],
 ['philotes','Philotes','Discord','A Discord bot exploring how friends coordinate and show up.',690,470],
 ['oversea','Oversea','Infrastructure','Containerised monitoring and access for web applications.',410,290],
 ['umami','Umami','Analytics / Fork','My fork of the open-source website analytics project.',170,470],
 ['sundance','Sundance','Creative hardware','A shared internet drawing board as an office ornament.',410,110],
 ['wamon','Wamon','Embedded / ESP32','Watering monitoring built with ESP-IDF.',410,470]
];
export function engineeringPage(){return `<section class="engineering-head"><p class="eyebrow">Engineering / System map</p><h1>Connected work.</h1><p>Small tools, shared services and things I build.</p></section><section class="systems-shell" aria-label="Interactive project map"><div class="systems-toolbar"><label>Find a project <input id="project-search" type="search" placeholder="Search projects" autocomplete="off"></label><button id="graph-motion" aria-pressed="false">Pause flow</button><button id="graph-in" aria-label="Zoom in">+</button><button id="graph-out" aria-label="Zoom out">−</button><button id="graph-reset">Reset view</button></div><div class="systems-layout"><div class="systems-viewport"><svg id="project-graph" viewBox="0 0 900 600" role="group" aria-label="Project relationships. Select a project for details."><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#ccd2d7"/></pattern></defs><rect width="900" height="600" fill="url(#grid)"/><g class="graph-content"><g class="graph-edges">${[[0,4],[4,1],[4,2],[4,3],[4,5],[4,6],[4,7]].map(([a,b],i)=>`<path class="graph-edge" d="M${projects[a][4]},${projects[a][5]} Q${(projects[a][4]+projects[b][4])/2+35},${(projects[a][5]+projects[b][5])/2-25} ${projects[b][4]},${projects[b][5]}"/><path class="graph-flow flow-${i}" d="M${projects[a][4]},${projects[a][5]} Q${(projects[a][4]+projects[b][4])/2+35},${(projects[a][5]+projects[b][5])/2-25} ${projects[b][4]},${projects[b][5]}"/>`).join('')}</g>${projects.map(([id,name,kind,description,x,y])=>`<g class="project-node" role="button" tabindex="0" aria-label="${name}: ${kind}" aria-pressed="false" data-project="${id}" data-name="${name}" data-kind="${kind}" data-description="${description}" transform="translate(${x} ${y})"><rect x="-79" y="-29" width="158" height="58" rx="7"/><circle cx="-62" cy="-5" r="3"/><text x="-49" y="-1">${name}</text><text class="node-kind" x="-49" y="16">${kind}</text></g>`).join('')}</g></svg><p class="graph-caption">Illustrative connections · not live traffic</p></div><aside class="project-detail" aria-live="polite"><p class="eyebrow">Project / <span id="project-index">01</span></p><h2 id="project-name">House</h2><p id="project-kind">Personal website</p><p id="project-description">Engineering, photography and the journal.</p><a id="project-link" href="https://github.com/designedbyjosh/house" rel="noreferrer">View repository ↗</a><div class="detail-note"><span class="eyebrow">Connections</span><p>This map groups public projects around shared infrastructure. Animated paths illustrate relationships, not measured integrations or service health.</p></div></aside></div><p id="graph-status" role="status"></p></section><nav class="project-directory" aria-label="All project repositories">${projects.map(([id,name])=>`<a href="https://github.com/designedbyjosh/${id}" rel="noreferrer">${name} ↗</a>`).join('')}</nav>`;}
