// The hero is a complete procedural 3D chamber; its poster is a frame of that scene.
export const oceanScene = `<div class="ocean-scene" aria-hidden="true"><div class="ocean-fallback"></div><canvas id="ocean-canvas"></canvas><div class="ocean-shade"></div></div>`;
const controls = `<p class="explore-hint" hidden>Drag to look around · Scroll to move · Esc to exit<br>Arrow keys to look · + / − to move</p><div class="scene-controls"><button class="explore-toggle" type="button" aria-pressed="false" hidden>Explore cave</button><button class="motion-toggle" type="button" aria-pressed="false" hidden>Pause motion</button></div>`;
export function homePage(cards) {
  return `<section class="ocean-hero" aria-labelledby="home-heading">
${oceanScene}
<div class="hero-content"><p class="eyebrow">Software engineer / Sydney</p><h1 id="home-heading">Joshua<br>Whitcombe<span class="name-period">.</span></h1><p class="hero-intro">Engineering, diving, photography and writing.</p><div class="hero-actions"><a class="text-link" href="#my-world">About & work <span aria-hidden="true">↓</span></a><a class="text-link" href="mailto:joshua@whitcombe.me">Contact <span aria-hidden="true">↗</span></a></div></div>
<div class="hero-bottom"><span class="scene-note">INTERACTIVE CAVE / 01</span>${controls}</div><div class="scroll-progress" aria-hidden="true"><span></span></div></section>
<section class="world-section section-wrap" id="my-world"><div class="section-kicker"><span>01 / About & work</span><span>Sydney, Australia</span></div><div class="world-heading"><h2>I’m Josh.</h2><p>I’m a software engineer based in Sydney. Outside work, I dive, take photographs and write.</p></div><div class="world-grid">
<a class="world-card" href="https://github.com/designedbyjosh" rel="noreferrer"><span class="eyebrow">01</span><h3>Engineering <span aria-hidden="true">↗</span></h3><p>Code and projects on GitHub.</p><span class="card-link">designedbyjosh</span></a>
<a class="world-card" href="/diving/"><span class="eyebrow">02</span><h3>Diving <span aria-hidden="true">↗</span></h3><p>Cave diving in Mexico and my Chowder Bay divemaster project.</p><span class="card-link">Stories & dive briefing</span></a>
<a class="world-card" href="/photography/"><span class="eyebrow">03</span><h3>Photography <span aria-hidden="true">↗</span></h3><p>Places and photographs from my journal.</p><span class="card-link">View the archive</span></a></div></section>
<section class="dive-feature section-wrap"><div class="dive-feature-copy"><p class="eyebrow">Diving</p><h2>From Sydney Harbour<br>to the cenotes of Mexico.</h2><a class="text-link" href="/diving/">Dive stories & projects <span aria-hidden="true">↗</span></a></div><span class="feature-footnote">3D CAVE STUDY</span></section>
<section class="writing-section section-wrap home-writing"><div class="section-kicker"><span>02 / Journal</span><a href="/articles/">All articles ↗</a></div><div class="journal-heading"><h2>Writing.</h2></div><ul class="article-grid">${cards}</ul></section>
<section class="contact-section section-wrap"><p class="eyebrow">Contact</p><h2><a href="mailto:joshua@whitcombe.me">Get in touch. <span aria-hidden="true">↗</span></a></h2><a class="back-top" href="#main">Back to top ↑</a></section>`;
}
export function divingPage() {
  return `<section class="ocean-hero diving-hero" aria-labelledby="diving-heading">${oceanScene}<div class="hero-content"><p class="eyebrow">Joshua Whitcombe / Diving</p><h1 id="diving-heading">Underwater<span class="name-period">.</span></h1><p class="hero-intro">Sydney Harbour. Mexico’s cenotes.<br>Dive projects and stories from the journal.</p><div class="hero-actions"><a class="text-link" href="#dive-project">Chowder Bay briefing <span aria-hidden="true">↓</span></a></div></div><div class="hero-bottom"><span class="scene-note">INTERACTIVE CAVE / 01</span>${controls}</div></section>
<section id="dive-project" class="section-wrap dive-project"><div class="section-kicker"><span>01 / Divemaster project</span><span>Sydney Harbour</span></div><div class="briefing-grid"><div><p class="eyebrow">Chowder Bay · Clifton Gardens</p><h2>Chowder Bay<br>dive briefing.</h2><p>A dedicated briefing for a Sydney Harbour dive, built as part of my divemaster work.</p><a class="button dark-button" href="https://chowder-bay-briefing.vercel.app/" rel="noreferrer">Open the briefing <span aria-hidden="true">↗</span></a><p class="access-note">The original project currently requires Vercel sign-in.</p></div><a class="briefing-cover" href="https://chowder-bay-briefing.vercel.app/" rel="noreferrer" aria-label="Open Chowder Bay dive briefing on Vercel (sign-in required)"><div class="cover-top"><span>DIVE BRIEFING / 01</span><span>↗</span></div><div class="bay-lines" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="cover-title"><span>SYDNEY HARBOUR</span><h3>Chowder<br>Bay.</h3><p>Joshua Whitcombe</p></div></a></div></section>
<section class="cave-story section-wrap"><div><p class="eyebrow">02 / From the journal</p><h2>Cave diving<br>in Mexico.</h2></div><div><p>Training with Juan in the cenotes around Tulum and Playa del Carmen, from introductory caverns to the TDI full cave course.</p><p>I wrote about the training, the places we dived, and what the experience meant to me after losing Aaron.</p><a class="text-link" href="/articles/becoming-a-cave-diver-in-mexico/">Read the article <span aria-hidden="true">↗</span></a></div></section>
<section class="contact-section section-wrap"><p class="eyebrow">Contact</p><h2><a href="mailto:joshua@whitcombe.me">Get in touch. <span aria-hidden="true">↗</span></a></h2><a class="back-top" href="/">Home ↗</a></section>`;
}
