// Authored presentation content. Original journal content stays in its existing pipeline.
export const oceanScene = `<div class="ocean-scene" aria-hidden="true"><img class="ocean-fallback" src="/ocean.svg" alt="" width="1400" height="1000"><canvas id="ocean-canvas"></canvas><div class="ocean-shade"></div></div>`;
const controls = `<div class="scene-controls"><span class="interaction-hint">Move your cursor. Find a little wonder.</span><button class="motion-toggle" type="button" aria-pressed="false" hidden>Pause motion <span aria-hidden="true">Ⅱ</span></button></div>`;
export function homePage(cards) {
  return `<section class="ocean-hero" aria-labelledby="home-heading">${oceanScene}<div class="hero-content"><p class="eyebrow"><span class="status-dot"></span> Software engineer · Sydney, Australia</p><h1 id="home-heading">A curious mind.<br><em>A little deeper.</em></h1><p class="hero-intro">G’day, I’m Josh. I build for the web, explore beneath the surface, and write about being human.</p><div class="hero-actions"><a class="button" href="#my-world">Explore my world <span aria-hidden="true">↓</span></a><a class="text-link" href="mailto:joshua@whitcombe.me">Say hello <span aria-hidden="true">↗</span></a></div></div><div class="scene-caption"><span class="crosshair">+</span><span>BELOW THE SURFACE<br><span class="caption-sub">A small world, worth exploring.</span></span></div><div class="hero-bottom"><a href="#my-world" class="scroll-cue"><span aria-hidden="true">↓</span> A little further down</a>${controls}</div><div class="depth-rail" aria-hidden="true"><span>THE SURFACE</span><div class="depth-ticks"></div><span id="depth-value">00</span></div></section>
<section class="world-section section-wrap" id="my-world"><div class="section-kicker"><span>01 / A few dimensions</span><span>Engineer. Diver. Human.</span></div><div class="world-heading"><h2>There’s more<br>to the surface.</h2><p>I’m a software engineer with a camera, a dive bag, and a habit of following my curiosity. This is where those parts of my life meet.</p></div><div class="world-grid"><a class="world-card" href="https://github.com/designedbyjosh" rel="noreferrer"><div class="world-icon engineering-icon" aria-hidden="true">&lt;/&gt;</div><span class="eyebrow">01 — Engineering</span><h3>Made with intention.</h3><p>Thoughtful software, useful ideas, and the details that make things work.</p><span class="card-link">Explore my GitHub <span aria-hidden="true">↗</span></span></a><a class="world-card" href="/diving/"><div class="world-icon diving-icon" aria-hidden="true"><span>↘</span></div><span class="eyebrow">02 — Underwater</span><h3>A different perspective.</h3><p>From Sydney’s harbour to Mexico’s caves. Less noise. More wonder.</p><span class="card-link">Come diving <span aria-hidden="true">↗</span></span></a><a class="world-card" href="/photography/"><div class="world-icon camera-icon" aria-hidden="true">◎</div><span class="eyebrow">03 — Photography</span><h3>Learning to notice.</h3><p>Places, people and the small things that are worth looking at twice.</p><span class="card-link">The photo journal <span aria-hidden="true">↗</span></span></a></div></section>
<section class="dive-feature section-wrap"><div class="contour-art" aria-hidden="true"><span>33° S<br>151° E</span></div><div class="dive-feature-copy"><p class="eyebrow">Beyond the keyboard</p><h2>Some of my favourite<br>places have no signal.</h2><p>Underwater, everything asks you to slow down. Pay attention. Stay curious. It’s a perspective I bring back to the surface.</p><a class="button" href="/diving/">The diving side of me <span aria-hidden="true">↗</span></a></div><span class="feature-footnote">SYDNEY HARBOUR & BEYOND</span></section>
<section class="writing-section section-wrap home-writing"><div class="section-kicker"><span>02 / Field notes</span><a href="/articles/">All writing <span aria-hidden="true">↗</span></a></div><div class="journal-heading"><h2>Life, in my own words.</h2><p>Adventure, grief, discovery.<br>And finding a little meaning along the way.</p></div><ul class="article-grid">${cards}</ul></section>
<section class="contact-section section-wrap"><p class="eyebrow">Always curious about what’s next</p><h2>Good things start<br>with a <a href="mailto:joshua@whitcombe.me">hello <span aria-hidden="true">↗</span></a></h2><a class="back-top" href="#main">Back to the surface ↑</a></section>`;
}
export function divingPage() {
  return `<section class="ocean-hero diving-hero" aria-labelledby="diving-heading">${oceanScene}<div class="hero-content"><p class="eyebrow">Away from the keyboard · Underwater</p><h1 id="diving-heading">A quieter<br><em>kind of wonder.</em></h1><p class="hero-intro">From the familiar waters of Sydney to the cenotes of Mexico. Diving is where I find focus, perspective, and a sense of something bigger.</p><div class="hero-actions"><a class="button" href="#dive-project">Explore the dive project <span aria-hidden="true">↓</span></a></div></div><div class="hero-bottom"><a href="#dive-project" class="scroll-cue">↓ &nbsp; Follow the line</a>${controls}</div></section>
<section id="dive-project" class="section-wrap dive-project"><div class="section-kicker"><span>01 / The divemaster project</span><span>Sydney Harbour</span></div><div class="briefing-grid"><div><p class="eyebrow">Chowder Bay · Clifton Gardens</p><h2>A local dive.<br>A considered briefing.</h2><p>My Chowder Bay briefing project brings the preparation for a Sydney Harbour dive into one dedicated place.</p><p>Built as part of my divemaster work, it connects two things I care about: diving and making information easier to use.</p><a class="button dark-button" href="https://chowder-bay-briefing.vercel.app/" rel="noreferrer">Open the dive briefing <span aria-hidden="true">↗</span></a><p class="access-note">Hosted on Vercel. The original project currently requires Vercel sign-in.</p></div><a class="briefing-cover" href="https://chowder-bay-briefing.vercel.app/" rel="noreferrer" aria-label="Open Chowder Bay dive briefing on Vercel (sign-in required)"><div class="cover-top"><span>FIELD GUIDE / 01</span><span>↗</span></div><div class="bay-lines" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><span>+</span></div><div class="cover-title"><span>SYDNEY HARBOUR</span><h3>Chowder<br>Bay.</h3><p>A dive briefing by Josh</p></div></a></div></section>
<section class="cave-story section-wrap"><div><p class="eyebrow">02 / Further from the surface</p><h2>Finding my flow<br>in the caves of Mexico.</h2></div><div><p>In Cancún, I met Juan. In the cenotes around Tulum and Playa del Carmen, I learned to see diving differently.</p><p>My cave training was about preparation, trust and keeping things simple. But it also became a story about grief, awe, and finding a little peace in a very quiet place.</p><a class="text-link" href="/articles/becoming-a-cave-diver-in-mexico/">Read the full story <span aria-hidden="true">↗</span></a></div></section>
<section class="dive-quote section-wrap"><p class="eyebrow">A note from my journal</p><blockquote>“You become inwardly focused, outwardly mindful and feel connectedness to the power of forces greater than yourself.”</blockquote><a href="/articles/becoming-a-cave-diver-in-mexico/">Becoming a cave diver in Mexico ↗</a></section><section class="contact-section section-wrap"><p class="eyebrow">Back on dry land</p><h2>A story to share?<br><a href="mailto:joshua@whitcombe.me">Say hello <span aria-hidden="true">↗</span></a></h2><a class="back-top" href="/">Back to the surface ↑</a></section>`;
}
