import {projects} from '../content/projects.mjs';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export {projects};
const icon='<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m12 2 9 5v10l-9 5-9-5V7zM3 7l9 5 9-5M12 12v10"/></svg>';
function explorer(slug='overview'){
 const live=['overview','blog'].includes(slug);
 return `<section class="system-explorer" data-explorer="${slug}" aria-label="Interactive service architecture and website activity">
 <div class="explorer-topbar"><span>${icon} SYSTEM EXPLORER <b>/ ${esc(slug.toUpperCase())}</b></span><span class="topbar-right" data-mode-label>${live?'WEBSITE ACTIVITY':'ARCHITECTURE WALKTHROUGH'}</span></div>
 <section class="traffic-panel" aria-label="Live website traffic">
  <div class="traffic-heading"><div><span class="micro">THE WEBSITE, RIGHT NOW</span><h2>A little window into the traffic.</h2></div><span class="traffic-state" data-traffic-state>Connecting…</span></div>
  <div class="traffic-stats"><div><span class="micro">ACTIVE ON THE SITE</span><strong data-active-site>—</strong><span>visible sessions · last 60 seconds</span></div><div><span class="micro">VIEWING THIS PAGE</span><strong data-active-page>—</strong><span>including you, if counting is on</span></div><div><span class="micro">PAGE VIEWS · 15 MIN</span><strong data-recent-views>—</strong><span>refreshes count as a new view</span></div><div class="traffic-chart"><span class="micro">VIEWS PER MINUTE</span><svg data-traffic-chart viewBox="0 0 450 80" role="group" aria-label="Views in each of the last 15 minutes"></svg><p data-chart-detail>Waiting for a shared traffic signal.</p></div></div>
  <div class="traffic-bottom"><span data-traffic-time>No live observation yet.</span><button data-traffic-refresh>Refresh ↻</button></div>
  <details class="traffic-details"><summary>What’s counted, and what stays private?</summary><p>These are approximate visible browser sessions, not identified people. A tab checks in every 20 seconds and expires after 60 seconds without a check-in. Counts update while this page is visible. Browser privacy signals and the footer opt-out are respected.</p><p>Only public page totals and minute buckets are shared. Short-lived random tokens are used for counting; this counter stores no IP addresses, account identities, referrers or query strings. Hosting providers may keep their normal request logs. Preview traffic is separate from production. Automated or blocked browsers can affect accuracy.</p><div class="active-pages" data-active-pages aria-label="Active sessions by public page"></div></details>
 </section>
 <div class="explorer-body"><div class="world-panel"><div class="world-tabs" role="group" aria-label="Map view"><button data-view="flow" aria-pressed="true">Data flow</button><button data-view="security" aria-pressed="false">Security</button><button data-view="health" aria-pressed="false">Live status</button></div><div class="scene-caption"><span class="micro">LOGICAL TOPOLOGY / PUBLIC VIEW</span><h2 data-scene-title>Explore the architecture</h2></div><canvas class="world-canvas" aria-label="Service map. Click a node or use the service selector to inspect it. Drag to pan; use buttons to zoom." tabindex="0"></canvas><p class="graphics-fallback" hidden>Graphics are unavailable. Use the service selector and text view to explore every node.</p><div class="camera-tools" role="group" aria-label="Map controls"><button data-camera="in" aria-label="Zoom in">＋</button><button data-camera="out" aria-label="Zoom out">−</button><button data-camera="reset" aria-label="Fit map">⌂</button><button data-fullscreen aria-label="Toggle fullscreen">⛶</button></div><div class="world-legend"><span><i class="legend-request"></i> <span data-legend>${live?'Observed page view':'Simulated request'}</span></span><span class="orbit-hint">Select a service · drag to pan</span></div></div><aside class="inspector"><div class="inspector-top"><span class="micro">SERVICE INSPECTOR</span><span data-node-count></span></div><div class="inspector-icon">${icon}</div><h3 data-node-title>Select a service</h3><p data-node-description>Choose a service node or use the selector below.</p><div class="inspector-divider"></div><span class="micro">TRUST BOUNDARY</span><p class="boundary-copy" data-node-security></p><div class="inspector-divider"></div><div class="status-row"><span class="micro">OBSERVED STATUS</span><span class="status-pill" data-node-status>Not monitored</span></div><p class="status-explanation" data-node-status-note>Private services are not probed by this page.</p><a class="inspector-link" data-project-link hidden>Explore this project ↗</a><label class="micro service-label" for="service-select">SELECT A SERVICE</label><select id="service-select" data-service></select></aside></div>
 <div class="activity-mode"><label>Show <select data-mode><option value="live"${live?' selected':''}>Live website activity</option><option value="walkthrough"${live?'':' selected'}>Architecture walkthrough</option></select></label><p data-mode-note>${live?'New page views send a dot along the public website path. No visits, no dots.':'A simulation of the permitted service flow. Private traffic is not monitored.'}</p></div>
 <div class="transport"${live?' hidden':''}><div class="transport-actions"><button class="play-button" data-play aria-pressed="true">Ⅱ Pause</button><button data-step>Step →</button><button data-trace>Trace request</button><button data-reset>Reset</button></div><label>Scenario <select data-scenario><option value="normal">Authorized request</option><option value="blocked">Access denied</option>${slug==='tesla'?'<option value="provider">Explicit provider operation</option>':''}</select></label><label class="speed-control">Speed <input type="range" min="0.3" max="2" step="0.1" value="0.8" data-speed aria-label="Animation speed"><output data-speed-value>0.8×</output></label></div>
 <div class="trace-strip" role="status" aria-live="polite"><span class="trace-label" data-trace-label>${live?'LIVE ACTIVITY':'SIMULATION'}</span><span data-trace-text>${live?'Waiting for newly observed page views.':'Illustrative traffic. Trace a request to follow each boundary.'}</span></div>
 <div class="status-drawer" hidden><div><span class="micro">PUBLIC REACHABILITY</span><h3>What’s reachable right now?</h3><p>Public page checks are independent of visitor counts and the walkthrough. They do not establish private service or database health.</p></div><div class="health-results"><div><span>This deployment</span><b data-local-status>Not checked</b></div><div><span>Public blog</span><b data-blog-status>Not checked</b></div><div><span>Private integrations</span><b>Not publicly monitored</b></div><p data-health-time>No observations yet.</p><button data-health-refresh>Check now ↻</button></div></div><noscript><p class="noscript-note">Enable JavaScript for live counts and the interactive map. Project descriptions and text architecture remain available below.</p></noscript></section>`;
}
const projectCards=()=>`<div class="project-directory">${projects.map((p,i)=>`<a class="directory-card" href="/projects/${p.slug}/"><span class="micro">0${i+1} / ${esc(p.category)}</span><div><h3>${esc(p.name)}</h3><span class="card-arrow">↗</span></div><p>${esc(p.summary)}</p><span class="directory-tag">${esc(p.tag)}</span></a>`).join('')}</div>`;
export function projectsIndex(){return `<div class="projects-shell"><header class="projects-hero"><div><p class="micro hero-kicker"><span class="live-dot"></span> JOSH’S LAB / SELECTED WORK</p><h1>Built to connect.<br><em>Open to explore.</em></h1><p>A living look inside the things I build. Pick a service, follow a request, and see where the boundaries are.</p></div><div class="hero-aside"><span>05</span><p>PROJECTS<br>ONE CONNECTED VIEW</p><a href="#project-directory">Explore the collection ↓</a></div></header>${explorer()}<section id="project-directory"><div class="directory-heading"><div><p class="micro">THE COLLECTION</p><h2>Small systems. Real purpose.</h2></div><p>Explore the architecture, one project at a time.</p></div>${projectCards()}</section><p class="lab-footnote">Public logical models · Website visits are measured; service walkthroughs are simulated · Private addresses, credentials and records are excluded</p></div>`;}
export function projectPage(p){return `<div class="projects-shell"><header class="project-hero"><a href="/projects/" class="lab-back">← The collection</a><p class="micro hero-kicker">${esc(p.category)} / ARCHITECTURE EXPLORER</p><h1>${esc(p.name)}<em>.</em></h1><p>${esc(p.summary)}</p></header>${explorer(p.slug)}<section class="project-story"><div><p class="micro">BEHIND THE BUILD</p><h2>${esc(p.tag)}.</h2><p>${esc(p.intro)}</p>${p.link?`<a href="${p.link}" class="inspector-link">${esc(p.linkText)} ↗</a>`:''}</div><div><details class="architecture-transcript" open><summary>Read the complete flow</summary><ol>${p.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p><strong>When access is denied:</strong> ${esc(p.blocked)}</p></details><p class="evidence-note">${esc(p.evidence)}</p></div></section><nav class="project-related" aria-label="More projects">${projects.filter(q=>q.slug!==p.slug).map(q=>`<a href="/projects/${q.slug}/">${esc(q.name)} ↗</a>`).join('')}</nav></div>`;}
