// Public conceptual topology only. Never import private configuration.
const n=(id,name,kind,x,z,color,description,boundary,project=null)=>({id,name,kind,position:[x,0,z],color,description,boundary,project});
const cyan=[.16,.89,.82],violet=[.61,.48,1],blue=[.28,.61,1],pink=[1,.40,.64],gold=[1,.72,.32];
const e=(a,b,label)=>({a,b,label});
export const scenes={
 overview:{title:'The connected picture',nodes:[
 n('client','MCP client','laptop',-6,0,cyan,'An assistant requests a tool through Model Context Protocol.','Input is never an authorization grant.','mcp-platform'),
 n('gateway','MCP access','gateway',-2,0,cyan,'The entry routes requests; each service performs its own access checks. Grouped here as one logical boundary.','Private service addresses are omitted.','mcp-platform'),
 n('discord','Discord bridge','server',3,-4,violet,'A dedicated bot connects an assistant to allowed conversations.','Read and send permissions are distinct.','discord'),
 n('tesla','Tesla service','car',4,0,blue,'Saved vehicle observations and separately gated navigation tools.','Vehicle identity, history and location stay private.','tesla'),
 n('whatsapp','WhatsApp bridge','phone',3,4,gold,'A linked-device bridge supplies messaging tools.','Device identity and messages stay private.','whatsapp'),
 n('reader','Reader','laptop',-6,-7,pink,'A browser requests a published article.','Only public writing is served.','blog'),
 n('blog','Blog delivery','cloud',-2,-7,pink,'A delivery layer serves the static journal.','Restrictive browser headers and HTTPS.','blog'),
 n('storage','Object storage','database',3,-7,pink,'Published files are retrieved through the delivery layer.','Direct public storage access is blocked.','blog')],edges:[e('client','gateway','Tool request'),e('gateway','discord','Authorized operation'),e('gateway','tesla','Authorized operation'),e('gateway','whatsapp','Authorized operation'),e('reader','blog','Page request'),e('blog','storage','Origin read on cache miss')],gate:'gateway'},
 blog:{title:'Publishing without the machinery',nodes:[
 n('reader','Reader','laptop',-6,1,pink,'The browser requests an article over HTTPS.','No login or private credentials needed.'),n('edge','Delivery layer','cloud',-2,1,pink,'The edge serves cached content or requests a static origin file.','HTTPS and restrictive response headers.'),n('origin','Private origin','database',3,-2,cyan,'Static files live in encrypted object storage.','Only the approved delivery layer can read origin files.'),n('page','Published assets','server',3,3,blue,'HTML, CSS and local scripts render the journal.','No admin APIs or private keys in browser assets.')],edges:[e('reader','edge','HTTPS request'),e('edge','origin','Authorized origin read'),e('edge','page','Cached page and assets'),{...e('reader','origin','Direct origin request'),deniedOnly:true}],gate:'origin'},
 'mcp-platform':{title:'One protocol. Purposeful connections.',nodes:[
 n('client','MCP client','laptop',-6,0,cyan,'The assistant selects a tool and supplies arguments.','Tool input does not grant access.'),n('entry','HTTPS entry','gateway',-2,0,cyan,'Encrypted requests are routed to a selected service.','Internal connection details stay private.'),n('auth','Authorization','shield',1,0,violet,'The selected service checks access before tool execution.','Identity and scope checks differ by service.'),n('discord','Discord','server',5,-4,violet,'Allowed bot conversation operations.','Read-only access cannot send messages.','discord'),n('tesla','Tesla','car',6,0,blue,'Saved observations and explicitly gated navigation.','Saved reads do not wake the vehicle.','tesla'),n('whatsapp','WhatsApp','phone',5,4,gold,'A linked-device messaging bridge.','Private messaging state stays server-side.','whatsapp')],edges:[e('client','entry','Encrypted tool request'),e('entry','auth','Validate access'),e('auth','discord','Permitted operation'),e('auth','tesla','Permitted operation'),e('auth','whatsapp','Permitted operation')],gate:'auth'},
 discord:{title:'An assistant with its own identity',nodes:[n('client','Assistant','laptop',-6,0,cyan,'Selects a conversation operation.','Messages are untrusted input.'),n('auth','Scope checks','shield',-2,0,violet,'Validates caller identity and the requested scope.','Read permission does not permit sending or editing.'),n('bridge','Bot bridge','server',2,0,violet,'Checks the allowed conversation and operation.','The bot cannot impersonate a personal account.'),n('provider','Discord API','cloud',6,-2,blue,'Processes a request using the bot identity.','Discord permissions still apply.'),n('events','Event subscriptions','database',2,4,gold,'Incoming events can notify a subscribed assistant.','Events do not authorize a reply.')],edges:[e('client','auth','Tool request'),e('auth','bridge','Permitted operation'),e('bridge','provider','Bot API call'),e('provider','events','Incoming event'),e('events','client','Subscribed notification')],gate:'auth'},
 tesla:{title:'Useful context. Deliberate actions.',nodes:[n('client','MCP client','laptop',-6,0,cyan,'Asks for saved status or a supported action.','No vehicle information is embedded here.'),n('auth','Owner authorization','shield',-2,0,blue,'Checks permission for the requested operation.','Navigation requires separate permission and an enabled capability.'),n('service','Vehicle service','server',2,0,blue,'Checks the allowed vehicle and selects the operation.','Default status reads use saved observations.'),n('history','Saved observations','database',6,-3,violet,'Returns previously collected snapshots.','Saved data has gaps; it is not a complete trip history.'),n('fleet','Fleet API','car',6,3,pink,'Explicit refresh or permitted navigation can reach the provider.','Saved reads do not call this path or wake the car.')],edges:[e('client','auth','Request'),e('auth','service','Authorized tool'),e('service','history','Default saved read'),{...e('service','fleet','Explicit provider operation'),optional:true}],gate:'auth'},
 whatsapp:{title:'A bridge to personal messaging',nodes:[n('client','MCP client','laptop',-6,0,cyan,'Requests a supported messaging tool.','This demo cannot read or send messages.'),n('auth','Authorization','shield',-2,0,gold,'Validates access before tool execution.','Invalid access stops here.'),n('bridge','Device bridge','phone',2,0,gold,'Translates permitted calls to linked-device operations.','Internal bridge access is authenticated.'),n('state','Private state','database',6,-3,violet,'Maintains local messaging and device state.','Messages, media and credentials are never published.'),n('network','Messaging network','cloud',6,3,cyan,'Exchanges supported linked-device operations.','Provider access does not bypass permission checks.')],edges:[e('client','auth','Tool request'),e('auth','bridge','Authenticated bridge call'),e('bridge','state','Local state'),e('bridge','network','Linked-device operation')],gate:'auth'}
};
export function flowEdges(scene,scenario='normal'){
 if(scenario==='blocked'){const direct=scene.edges.filter(e=>e.deniedOnly);if(direct.length)return direct;const result=[];const queue=[scene.nodes[0].id];const seen=new Set();while(queue.length){const id=queue.shift();if(seen.has(id)||id===scene.gate)continue;seen.add(id);for(const edge of scene.edges.filter(e=>e.a===id)){result.push(edge);queue.push(edge.b);}}return result;}
 return scene.edges.filter(edge=>!edge.deniedOnly&&(!edge.optional || scenario==='provider'));
}
